### ISSUE TITLE
bug: error if used against strings >4MB

### ISSUE THREAD

**Issue by wuputah** [hydradatabase/pg_stringtheory#7]
In testing on a m6a.4xl (x86_64) machine, stringtheory works on strings that are 2^22 (4MB) in length:

```
=> insert into t select repeat('a', (2^22)::integer);
INSERT 0 1
=> select count(*) from t where stringtheory.strstr(s, 'b') != -1;
 count
-------
     0
(1 row)
```

but errors at 2^23 (8MB) in length:

```
=> insert into t select repeat('a', (2^23)::integer);
INSERT 0 1
=> select count(*) from t where stringtheory.strstr(s, 'b') != -1;
SSL SYSCALL error: Undefined error: 0
```

This is presumably due to allocating strings on the stack, which works well for small strings but not a great idea for large strings. A threshold for using the heap instead, perhaps 2^16 (64kiB) to 2^20 (1MiB) might be a good idea.

**Comment by JerrySievert** [comment]
fixed with #8
